[package]
name = "routetype-warp"
version = "0.1.0"
authors = ["Michael Snoyman <michael@snoyman.com>"]
edition = "2018"

[dependencies]
routetype = { path = "../routetype" }
warp = "0.3"
async-trait = "0.1.50"
