[package]
name = "routetype-derive"
version = "0.1.0"
authors = ["Michael Snoyman <michael@snoyman.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.69", features = ["full"] }
quote = "1.0.7"
proc-macro2 = "1.0"
anyhow = "1"
